### ISSUE TITLE
Secret in the config

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/ark-node#10]
Not sure if this is possible, but is there some way to encrypt the secret in the config file? I just don't like the idea of seeing my secret in the plain text file, what if the server got hacked?

**Comment by boldninja** [comment]
Currently this hasn't been implemented yet for now set 2nd passphrase on forging account as that one won't be saved on server and don't have huge amount on that delegate account so even if somehow you got hacked there won't be much to be taken.

**Comment by fix** [comment]
We have some ideas about securing the passphrase, that will be implemented in a short term milestone.

Keep in mind the following: encrypting is useless since you need to provide the key in the config file to decrypt the passphrase so it can be used to sign blocks...

If you register a second passphrase, it won't appear anywhere in config file, it will lock the fund anyway in the account. However it can harm you since somebody else could enable forging on the network and prevent your delegate functioning correctly.

**Comment by faustbrian** [comment]
As Core 2.0 is under development we will close all the PRs and Issues regarding Core 1.0 and only handle critical issues if any come up.
